### ISSUE TITLE
Serial input causes panic

### ISSUE THREAD

**Issue by klange** [heatd/Onyx#40]
Using the CI build of `disk-image.img` from https://github.com/heatd/Onyx/actions/runs/2907275605 (produced from https://github.com/heatd/Onyx/commit/2cec04e348a2d473789692a3a9721d978843ebe1) and the following QEMU incantation:

    qemu-system-x86_64 -drive file=disk-image.img,format=raw,media=disk -boot d -enable-kvm -m 1G -cpu host,migratable=on,+invtsc -smp 4 -vga qxl -device usb-ehci -device usb-mouse -machine q35 -bios /usr/share/qemu/OVMF.fd  -netdev user,id=u1 -device virtio-net,netdev=u1 -serial stdio

Attempting to use the resulting serial console immediately results in a panic on the first key stroke:

![Screenshot from 2022-08-23 07-17-34](https://user-images.githubusercontent.com/223546/186032912-52361013-8a5f-46bd-b980-abbecd7608f0.png)

No further output beyond `/bin/login: username:` is evident in the serial console.

For additional reference, two builds of QEMU were used with the same results:
- `QEMU emulator version 4.2.1 (Debian 1:4.2-3ubuntu6.23)`
- `QEMU emulator version 6.2.92 (v6.0.0-8451-gb992cef642)`

And since I am using `-cpu host` as requested, the host CPU is a `Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz` (Q3'15 Skylake, poor old thing is in dire need of replacement).

**Comment by heatd** [comment]
Fixed in fc8fee4.

Thank you for flying Air Onyx.
