### ISSUE TITLE
 error: 'ACPI_STATUS' does not name a type; did you mean 'ACPI_STATE_S0'?

### ISSUE THREAD

**Issue by zoe-vb** [heatd/Onyx#62]
This issue arose using the latest gcc toolchain and latest sysroot when running make iso

**Comment by heatd** [comment]
Hi!

What kernel config are you using?
git grep ACPI_STATUS shows me 2 buggy references to this old type, but both are conditional on CONFIG_ACPI not being defined. Which in all honesty, you probably want defined.

**Comment by zoe-vb** [comment]
kernel.config.minimal

**Comment by heatd** [comment]
Ah yes, to be fair, kernel.config.minimal is not very useful as an operating system (and I don't test with it). Please use one of the configs under kernel/configs, or specify CONFIG_ACPI=y.

I'll keep this open to track the build issue with CONFIG_ACPI=n.
